---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: centos7
    playbook: test.yml
    GIFLOSSY_VERSION: 1.91
  - distro: centos6
    playbook: test.yml
    GIFLOSSY_VERSION: 1.91
  - distro: ubuntu1404
    playbook: test.yml
    GIFLOSSY_VERSION: 1.91
  - distro: debian8
    playbook: test.yml
    GIFLOSSY_VERSION: 1.91

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_idempotence=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure gifsicle is installed and at the right version.
  - 'docker exec --tty ${container_id} env TERM=xterm which gifsicle'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x /usr/local/bin/gifsicle'

  - 'docker exec --tty ${container_id} env TERM=xterm gifsicle --version'
  - 'docker exec --tty ${container_id} env TERM=xterm /usr/local/bin/gifsicle --version | grep -qF "$GIFLOSSY_VERSION"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/