---
- name: install packages for building gifsicle
  yum: 
    name:
      - "@Development tools"
      - automake
    state: present
  when: ansible_os_family == 'RedHat'

- name: install packages for building gifsicle
  apt: 
    name:
      - build-essential
      - autoconf
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: download gifsicle source
  get_url:
    url: "https://github.com/kohler/gifsicle/archive/refs/tags/v{{ gifsicle_version }}.tar.gz"
    dest: /opt/gifsicle-{{ gifsicle_version }}.tar.gz

- name: Extract gifsicle
  unarchive:
    src: "/opt/gifsicle-{{ gifsicle_version }}.tar.gz"
    dest: /opt
    remote_src: yes

- name: make configure gifsicle
  shell: "autoreconf -i"
  args:
    chdir: "/opt/gifsicle-{{ gifsicle_version }}/"

- name: configure gifsicle
  command: ./configure {{ gifsicle_options|join(' ') }}
  args:
    chdir: "/opt/gifsicle-{{ gifsicle_version }}/"
    

- name: build gifsicle
  command: make
  args:
    chdir: "/opt/gifsicle-{{ gifsicle_version }}/"

- name: install gifsicle
  command: make install
  args:
    chdir: "/opt/gifsicle-{{ gifsicle_version }}/"
  